select * from employees;
-- 1. FIND OUT COUNTRY NAME AND REGION NAME FROM COUNTRIES AND REGION TABLE

select country_name, REGION_NAME
from COUNTRIES c inner join REGIONS r on c.REGION_ID = r.REGION_ID;


-- 2. FIND OUT FIRST_NAME AND JOB_TITLE FROM JOBS AND EMPLOYEES TABLE
select FIRST_NAME,JOB_TITLE
from EMPLOYEES e join JOBS J on e.JOB_ID = J.JOB_ID;


select FIRST_NAME,JOB_TITLE
from EMPLOYEES e join JOBS J on e.JOB_ID = J.JOB_ID;


-- 3. FIND OUT DEPARTMENT_NAME AND CITY
select  DEPARTMENT_NAME, CITY
from DEPARTMENTS d inner join LOCATIONS l  on d.LOCATION_ID = l.Location_id;



-- 4. FIND OUT ALL CITIES  AND COUNTRY NAMES
select city, COUNTRY_NAME
from COUNTRIES c inner join LOCATIONS l on c.COUNTRY_ID=l.Country_id;

-- 5. FIND OUT FIRST_NAME, LAST NAME, DEPARTMENT ID , DEPARTMENT NAME  FOR DEPARTMENT ID 80 OR 40
select FIRST_NAME, LAST_NAME,DEPARTMENT_NAME, d.DEPARTMENT_ID
from DEPARTMENTS d inner join EMPLOYEES e on d.DEPARTMENT_ID = e.DEPARTMENT_ID
where d.DEPARTMENT_ID in (40,80);


-- 6. FIND OUT CITY , COUNTRY_NAME OF THAT CITY , REGION_NAME OF THAT CITY
select CITY, c.COUNTRY_NAME,r.REGION_NAME
from LOCATIONS l
    inner join COUNTRIES c  on C.COUNTRY_ID = l.COUNTRY_ID
inner join REGIONS r on c.REGION_ID = r.REGION_ID;


--  7. FIND OUT EMPLOYEES FIRST_NAME , JOB_TITLE , DEPARTMENT_NAME , CITY
select FIRST_NAME, JOB_TITLE, DEPARTMENT_NAME, CITY
from jobs j inner join EMPLOYEES e on j.JOB_ID=e.JOB_ID
            inner join DEPARTMENTS d on d.DEPARTMENT_ID= e.DEPARTMENT_ID
            inner join LOCATIONS l on l.LOCATION_ID=d.LOCATION_ID;

-- 8. FIND OUT EMPLOYEES FIRST_NAME , JOB_TITLE , DEPARTMENT_NAME , CITY , COUNTRY_NAME , REGION_NAME





--9. FIND OUR  EMPLOYEES FIRST_NAME, LAST NAME, DEPARTMENT ID AND ALL DEPARTMENTS
--  INCLUDING  WHERE DO NOT HAVE ANY EMPLOYEE.

select  * from DEPARTMENTS;
select * from EMPLOYEES;

select first_Name,LAST_NAME, d.DEPARTMENT_ID
from DEPARTMENTS d left outer join EMPLOYEES e on d.DEPARTMENT_ID;



--10. FIND OUT ALL DEPARTMENT_NAME  , LOCATION_ID , AND COUNTRY_ID
-- INCLUDING THOSE LOCATIONS  WITH NO DEPARTMENT




--11.FIND OUT DEPARTMENT_NAME , LOCATION_ID , AND COUNTRY_NAME
-- INCLUDING THOSE COUNTRIES WITH NO DEPARTMENT



--12. FIND OUT EMPLOYEES FIRST_NAME, DEPARTMENT ID AND DEPARTMENT NAME
-- INCLUDING THOSE DOES NOT HAVE DEPARTMENT
-- INCLUDING THOSE DEPARTMENTS  DOES NOT HAVE ANY MATCHING EMPLOYEES

select FIRST_NAME, d.DEPARTMENT_ID, DEPARTMENT_NAME

from EMPLOYEES e full outer join DEPARTMENTS d on d.department_id=e.DEPARTMENT_ID;
